<div class="tody-the-most-column">
	<ul class="cls">
		<li>
			<div class="item-grts xinxian"><h4>个性</h4></div>
			<a class="link-box" href="#" target="_blank"><img src="/static/img/280_280.jpg" alt="" width="280" height="280"><strong>先打手枪再起床</strong></a>						
		</li>
		<li>
			<div class="item-grts tebie"><h4>特别</h4></div>
			<a class="link-box" href="#" target="_blank"><img src="/static/img/280_280.jpg" alt="" width="280" height="280"><strong>你会用罐头做的掌上钢琴吗？</strong></a>						
		</li>
		<li>
			<div class="item-grts wenyi"><h4>舒适</h4></div>
			<a class="link-box" href="#" target="_blank"><img src="/static/img/280_280.jpg" alt="" width="280" height="280"><strong>手工懒人鞋 舒不舒服脚知道</strong></a>						
		</li>			
	</ul>
</div>